name: 'Setup DCM'
description: 'Download and setup DCM'
author: 'dcm.dev'

branding:
  color: 'blue'
  icon: 'search'

inputs:
  github_token:
    description: 'Token to connect to GitHub. Use secrets.GITHUB_TOKEN.'
    required: true
  version:
    description: The version of the executable to install (ex. 'latest', '1.6.0').
    required: false
    default: 'latest'

runs:
  using: 'node16'
  main: 'dist/index.js'
